### PR TITLE
Added client interfaces and dummies

### PR DESCRIPTION
**Pull request by drieschel**
I added interfaces, so they can used as strategy and dummy clients for basic initialization. In this way real clients can be set only if needed.

### CODE REVIEW

**Comment by Milanowicz** [comment]
We running under PHP 8 and I suppose something here, I want to share it and not throw away.
- feature/client_interfaces_and_dummies_php_8

In new Interfaces or Classes is the PHP declare for strict mode are missing.

**Comment by sleipi** [comment]
Hi @drieschel 

thanks for the PR

First, I would not add those Dummy integrations into this repository. Even the Interfaces seems to be unnecessary. 
Because it is always up to your integration to handle the behavior if you need to use these clients or not. For Example, you could use a ENV variable to indicate if GoPrometrics is installed in a specific Environment

something like this
```php
class GoPrometricsService
{
    private Counter $counter;
    private bool $isActive;

    public function __construct(Counter $counter)
    {
        $this->counter = $counter;
        $this->isActive = $_ENV['USE_GOPROMETRICS'] ?? false;
    }

    public function count(string $ns, string $name): void
    {
        if($this->isActive) {
            $this->counter->count($ns, $name);
        }
    }
}
```

Furthermore, it is also a good practice to not use 3rd Party Dependencies directly in your core Code. Encapsulate those dependencies like shown in the code example - with this you are free to add you own logic around - like checking if a software is running on a given environment.

Another Example: When using a Database, you will probably hide CRUD operations behind a Repository class or even a whole ORM

But maybe I don't complete understand you use-case. Could you show some example code, how would you like to use it in your integration with?

**Comment by sleipi** [comment]
@Milanowicz 
https://github.com/jtl-software/goprometrics-client/pull/32#issuecomment-911783773

Lets keep the discussion in this issue. Ok, lets keep the interface - i am fine with that, even when I think they are unnecessary. 

Does it make a different to mock a Class instead of Interface?

**Comment by Milanowicz** [comment]
I use Interfaces for Dependency Injection, other declarations and to prophsizing the behavior by Testing for this or that.

I vote to keep interfaces :+1: :1st_place_medal: 

Dummy classes, I'm not so great with them like @sleipi see that too. Because we've a GoPrometricsService class already.

"Does it make a different to mock a Class instead of Interface?" Not really, both does the same with help by this "ReflectionClass". Big Classes could take some time, Interfaces usally always smaller then classes.

**Comment by sleipi** [comment]
> Big Classes could take some time, Interfaces usally always smaller then classes.

Yeah! If you could measure the difference on more less modern machine a it take longer than a second for 100k runs i owe you a beer. Maybe two :beers: 

Ok. Lets keep the Interfaces - no lets so that #32 becomes ready merge ;)

**Comment by drieschel** [comment]
Hi @sleipi,

I want to use the GoPrometrics client in different libs. For instance I want to integrate it in a rest client. At this point it is not clear where the rest client is used. Because of this, the rest client does not have any information about environments, it is a lib and not an application. Idea is to instantiate a class property with a dummy (ie. HistogramDummy) in the constructor of the rest client. In this way the class property can be used like if it's a real client and no checks are needed to make sure if it is in the "right" environment or not. Just the application which uses the rest client can decide if data should get send to a GoPrometrics server or not, by setting a real counter, histogram or gauge instance in the rest client.

**Comment by sleipi** [comment]
Thanks @drieschel 

Ok, I understand - Thanks. Are you fine with it to leave the Dummy implementations up to you? So with the Interfaces you can do what ever you want. Building your own Dummy Implementation and use it as a Argument.

But I would also suggest not doing so. Encapsulate the whole goprometrics-client and use this implementation when creating instances in your Rest Client. 


Let assume your RestClient provide have a Interface MonitoringService
```php
interface MonitoringService
{
    public function count(): void;
}
```
and two implentations

A Real one which communicate which GoPrometrics
```php
class MyGoPrometricyMonitorngService implements MonitoringService
{
    private Counter $counter;

    public function __construct(Counter $counter)
    {
        $this->counter = $counter;
    }

    public function count(Metric $metric): void
    {
        $this->counter->count($metric->ns, $metric->name);
    }
}
```

And also a Dummy
```php
class MyDummyMonitoringService implements MonitoringService {
    public function count(): void
    {
        /* relax */
    }
}
```

And now with your RestClient. Inject the MonitorService Interface and Voila.
You don't even need the interfaces from this PR in here.

```php
class RestClient
{
    private ClientInterface $httpClient;
    private MonitoringService $monitoringService;

    public function __construct(ClientInterface $httpClient, MonitoringService $monitoringService)
    {
        $this->httpClient = $httpClient;
        $this->monitoringService = $monitoringService;
    }

    public function doSomeRestfulThinks(Request $request)
    {
        /* summon dragons here */
    }
}
```

And there is even more advantages behind this approach. Consider you need to use another Monitoring System, instead of unknown not so well documented GoPrometrics stuff. Lets assume a Database would be exactly the right choice.

```php
class MyDatabaseBasedMonitoringService implements MonitoringService
{
    private MyDatabaseConnection $dbConn;

    public function __construct(MyDatabaseConnection $dbConn)
    {
        $this->dbConn = $dbConn;
    }

    public function count(): void
    {
        $this->dbConn->exec("INSERT INTO monitoring ...");
    }
}
```

What do you think?

**Comment by drieschel** [comment]
@sleipi,

thanks for the proposal. Creating a wrapper could be another possibility, sure. I see the benefit of it but I don't need it now. Maybe later when things are growing and we use different mechanisms for "monitoring". First I want to start "monitoring" stuff at all. I didn't want to create another repository, because I see the benefit one maintained repository, where lots of people are working on, instead of lots of unmaintained forks. As I already said, I think the dummies would fit here and they don't affect the actual state of the clients. But if you are uncool with it, I will find another solution.

**Comment by sleipi** [comment]
@drieschel - but you already have two different mechanisms for "monitoring". The real usage of GoPrometrics and the Dummy. 
My proposal fit exactly your need.

> I think the dummies would fit here and they don't affect

I my opinion they don't belongs to this client. This would be a feature only for your need - no other user would benefit from having such Dummies. 

In JTL-EazyAuction we have (maybe) nearly the same situation, some environments have a installed GoPrometrics Server some don't. So our Applications have to deal with it. Maybe a can show you how we solve this.

**Pull request merged**
